from os import path
#定义训练数据和验证数据的路径
TRAIN_IMAGES="datasets/tiny-imagenet-200/train"
VAL_IMAGES="datasets/tiny-imagenet-200/val/images"
#定义将验证文件名映射到其对应的类标签的文件的路径
VAL_MAPPINGS="datasets/tiny-imagenet-200/val/val_annotations.txt"
#定义用于生成类标签的wordNet层次结构文件的路径
WORDNET_IDS="datasets/tiny-imagenet-200/wnids.txt"
WORD_LABELS="datasets/tiny-imagenet-200/words.txt"
#由于无法访问测试数据，因此需要从训练数据中获取图像使用
NUM_CLASSES=200
NUM_TEST_IMAGES=50*NUM_CLASSES
#定义输出训练、验证和测试HDF5文件的路径
TRAIN_HDF5="datasets/tiny-imagenet-200/hdf5/train.hdf5"
VAL_HDF5="datasets/tiny-imagenet-200/hdf5/val.hdf5"
TEST_HDF5="datasets/tiny-imagenet-200/hdf5/test.hdf5"
#定义数据平均值的路径
DATASET_MEAN="output/tiny-imagenet-200-mean.json"
#定义存储绘图，分类报告等的输出目录的路径
OUTPUT_PATH="output"
MODEL_PATH=path.sep.join([OUTPUT_PATH,"resnet_tinyimagenet_decay.hdf5"])
FIG_PATH=path.sep.join([OUTPUT_PATH,"resnet56_tinyimagenet.png"])
JSON_PATH=path.sep.join([OUTPUT_PATH,"resnet56_tinyimagenet.json"])